#!/bin/sh

# Change `style.css` or `style.min.css` to whatever you would like your compiled
# stylesheet to be called. Do not rename `style.scss` or alter references to it.

# No minification
#sass --watch style.scss:style.css --style expanded

sass --watch yellow.scss:css/yellow.min.css --style compressed --sourcemap
sass --watch yellow.scss:css/yellow.max.css --style expanded --sourcemap

exit 0
